GET http://localhost:8800/api/admin/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGFtb24iLCJpYXQiOjE2OTIwODMzMDcsImV4cCI6MTY5MjA4MzM2N30.tSK9Z44QSQG4WbEvujdv4t4My5_qTdCE8Xz-jS-uLKY
###

POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "username": "damon",
    "password": "Abhijith1"
}

###

POST http://localhost:8800/api/auth/refresh-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGFtb24iLCJpYXQiOjE2OTIwODMyMDl9.8ejnN0Yw7beHF79V1dTyhv3n9Xq9RSU1yCv4rgKOQsM"
}

###
DELETE http://localhost:8800/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGFtb24iLCJpYXQiOjE2OTIwMjY1MjF9.TKS8aTXVxf98JSd_fpTzd-42d6wFM295w1qFCRfDOAk"
}